# Generated by Django 4.2.13 on 2024-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this item appears in the carousel')),
                ('link', models.URLField(blank=True, help_text='Optional link for the button')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
