# Generated by Django 4.2.13 on 2024-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='', max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('symbol', models.CharField(default='+', max_length=10)),
            ],
        ),
    ]
