# Generated by Django 4.2.13 on 2024-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_achievementitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementitem',
            name='icon_class',
            field=models.CharField(default='fa-heart', max_length=50),
        ),
    ]
